# Generated by Django 4.1 on 2023-01-03 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News_Data",
            fields=[
                ("news_id", models.AutoField(primary_key=True, serialize=False)),
                ("link_n", models.CharField(max_length=400)),
                ("headline", models.CharField(max_length=400)),
                ("category", models.CharField(max_length=100)),
                ("date_d", models.DateField(null=True)),
                ("authors", models.CharField(max_length=100)),
                ("short_description", models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name="Top_Status",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("cpu_optimiztion", models.CharField(max_length=400)),
                ("mem_bytes", models.CharField(max_length=400)),
                ("swap_file_bytes", models.CharField(max_length=400)),
                ("added_date", models.DateField(auto_now_add=True)),
                ("added_time", models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Store_File",
            fields=[
                ("file_id", models.IntegerField(primary_key=True, serialize=False)),
                ("file_s", models.FileField(upload_to="uploded_files/")),
                (
                    "user_id_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
